### ISSUE TITLE
Networking crash dump

### ISSUE THREAD

**Issue by CorruptData** [WJLiddy/204x#1]
Traceback (most recent call last):
  File "testclient.py", line 90, in <module>
    gameinfo = recv(sock)
  File "testclient.py", line 14, in recv
    return json.loads(recv)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 2 column 6 (char 7723 - 7728)

**Comment by WJLiddy** [comment]
Averted in the unity version. I will not really be supporting the test client too much longer.
